// Commented out means it is excluded.
const VALID_FIELDS = [
    "text",
    "fill",
    "stroke",
    "strokeWidth",
    "opacity",
    "padding",
    "fontSize",
    "fontFamily",
    "fontStyle",
    "fontWeight",
    "lineHeight",
    "textAlign",
    "underline",
    // "textBackgroundColor",
    "borderColor",
    "borderRadius",
    // "zOrder",
    // "backgroundColor", // strangely resets to black after first apply.

    // ^ these are all good, leave to enable.

    // "shadow",
    // "direction",
    // "firstText",
    // "skewX",
    // "skewY",
    // "cornerColor",
    // "cornerStrokeColor",
    // "rotatingPointOffset",
    // "cornerSize",
    // "startAngle",
    // "endAngle",
    // "d",
    // "colorHash",
    // "colorImage",
    // "height",
    // "width",
    // "angle",
    // "top",
    // "left",
    // "filters",
    // "rx",
    // "ry",
    // "lineCoords",
    // "src",
    // "lockScalingX",
    // "lockScalingY",
    // "lockUniScaling",
    // "lockRotation",
    // "lockMovementX",
    // "lockMovementY",
    // "hasRotatingPoint",
    // "hasControls",
    // "shapeImageSrc",
    // "idx",
    // "selected",
    // "scaleX",
    // "scaleY",
    // "crossOrigin",
    // "strokeUniform",
    // "strokeDashArray",
    // "strokeDashOffset",
    // "underline",
    // "overline",
    // "canvas",
    // "aCoords",
    // "oCoords",
    // "charSpacing",
    // "clipPath",
    // "clipTo",
    // "dirty",
    // "fillRule",
    // "flipX",
    // "flipY",
    // "group",
    // "isMoving",
    // "linethrough",
    // "mouseMoveHandler",
    // "originX",
    // "originY",
    // "paintFirst",
    // "path",
    // "pathOffset",
    // "points",
    // "shapeImage",
    // "strokeLineCap",
    // "strokeLineJoin",
    // "strokeMiterLimit",
    // "styles",
    // "textLines",
    // "transformMatrix",
    // "type",
    // "uuid",
    // "version",
    // "visible",
    // "zoomX",
    // "zoomY",
    // "overflow",
    // "enable-background",
    // "xlink:href",
    // "toBeParsed",
    // "white-space",
    // "fromSVG",
    // "bbox",
    // "viewBoxTransform",
    // "viewBoxHeight",
    // "viewBoxWidth",
    // "svgUid",
    // "id",
    // "cropX",
    // "cropY",
    // "textAlign",
    // "textState",
    // "minX",
    // "minY",
    // "clipRule",
];

export default VALID_FIELDS;
